# -*- coding: utf-8 -*-
"""numpy_assig.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TRH3GhqKF6rS4Ik6b_gFwQ9hNjYfOEBY
"""

# Create a null vector of size 10 but the fifth value which is 1.

import numpy as np

null_vector = np.zeros(10)
null_vector[4] = 1

print(null_vector)

# Create a vector with values ranging from 10 to 49.

vector = list(range(10, 50))
print(vector)

# Create a 3x3 matrix with values ranging from 0 to 8

import numpy as np

matrix = np.arange(9).reshape(3, 3)
print(matrix)

# Find indices of non-zero elements from [1,2,0,0,4,0].

import numpy as np

arr = np.array([1, 2, 0, 0, 4, 0])
nonzero_indices = np.nonzero(arr)[0]
print(nonzero_indices)

# Create a 10x10 array with random values and find the minimum and maximum values.

import numpy as np

# Create a 10x10 array with random values between 0 and 1
array = np.random.rand(10, 10)

# Find the minimum and maximum values in the array
min_value = np.min(array)
max_value = np.max(array)

print("Minimum value:", min_value)
print("Maximum value:", max_value)

# Create a random vector of size 30 and find the mean value.

import numpy as np

# Create a random vector of size 30
vector = np.random.rand(30)

# Find the mean value of the vector
mean_value = np.mean(vector)

print("Mean value:", mean_value)